Update release.yaml

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -31,6 +31,7 @@ jobs:
       - name: Extract commit data
         uses: rlespinasse/git-commit-data-action@v1.x
       - name: Get tag
+        id: mod
         shell: bash
         run: |
           git config --global user.name "Madman10K"
@@ -38,6 +39,7 @@ jobs:
           git fetch --all
           git submodule update --remote --merge --init --recursive
           ver="${{ github.ref_name }}"
+          echo "out=uvk-build-tool-${ver:1}" >> $GITHUB_OUTPUT
           sed -i "s/project(UVKBuildToolLib.*/project(UVKBuildToolLib VERSION ${ver:1})/g" CMakeLists.txt
           sed -i "s/project(UVKBuildTool .*/project(UVKBuildTool VERSION ${ver:1})/g" CMakeLists.txt
           (git add . && git commit -m "Automatically bump version" && git push origin HEAD:master) || echo "Nothing to commit"
@@ -45,7 +47,11 @@ jobs:
         shell: bash
         run: |
           rm -rf .git/
-          tar cfJ uvk-build-tool.tar.xz . || echo "Might have failed"
+          mkdir "${{ steps.mod.outputs.out }}" || exit
+          mv * ${{ steps.mod.outputs.out }}/ || echo "Errors in move"
+          mv .* "${{ steps.mod.outputs.out }}" || echo "Errors in move"
+
+          tar cfJ ${{ steps.mod.outputs.out }}.tar.xz ${{ steps.mod.outputs.out }} || echo "Might have failed"
       - name: Create Release
         uses: softprops/action-gh-release@v2
         with:
@@ -54,5 +60,5 @@ jobs:
             More on what is done this month can be found on the latest newsletter entry: https://madladsquad.com/#monthly-newsletter
           draft: false
           prerelease: false
-          files: uvk-build-tool.tar.xz
+          files: ${{ steps.mod.outputs.out }}.tar.xz
           generate_release_notes: false
